"""Named map sites. bearing: 0=N, 90=E. crates: (items, vault_cost|None). structs: (dx,dy,w,h)."""
DEFS = [
 dict(id="capsule", name="Cargo Capsule Wreck", kind="wreck", bearing=250, dist=700, known=True, range=900, ring=110,
      desc="Debris from the supply shipment that never arrived.", structs=[(0, 0, 70, 44)],
      crates=[([("iron_scrap", 3)], None), ([("aluminum", 2), ("polymer", 2)], None), ([("food_ration", 1), ("water", 1)], None)]),
 dict(id="craters", name="Impact Crater Field", kind="crater", bearing=20, dist=1300, range=800, ring=150, desc="Iron-rich meteorite fragments.",
      structs=[], crates=[([("iron_scrap", 2)], None), ([("iron_scrap", 2)], None), ([("iron_scrap", 3), ("aluminum", 1)], None), ([("regolith", 3)], None)]),
 dict(id="cache7", name="Emergency Cache 7", kind="cache", bearing=300, dist=1700, range=900, ring=70, desc="Marked survival cache of an earlier crew.",
      structs=[(0, 0, 34, 34)], crates=[([("food_ration", 2), ("water", 1)], None), ([("medical", 1), ("oxygen_tank", 1)], None)]),
 dict(id="rover_wreck", name="Old Mars Rover", kind="wreck", bearing=40, dist=2100, range=900, ring=120, desc="A dead rover. Parts may be salvageable.",
      structs=[(0, 0, 90, 50)], crates=[([("mechanical_parts", 2), ("battery", 1)], None), ([("aluminum", 3), ("electronics", 1)], None), ([("copper", 1)], None)]),
 dict(id="solar_wreck", name="Broken Solar Array", kind="wreck", bearing=170, dist=2700, range=900, ring=150, desc="Toppled panels and cabling.",
      structs=[(-60, 0, 14, 90), (0, 0, 14, 90), (60, 0, 14, 90)],
      crates=[([("solar_component", 2)], None), ([("copper", 2), ("glass", 1)], None), ([("aluminum", 2)], None)]),
 dict(id="buried", name="Buried Equipment", kind="buried", bearing=80, dist=3300, range=140, ring=0, hidden=True, desc="A sealed equipment case under the dust.",
      structs=[], crates=[([("tools", 1), ("electronics", 2), ("mechanical_parts", 1)], None)]),
 dict(id="kepler", name="Research Station Kepler", kind="station", bearing=350, dist=3800, range=1000, ring=190, desc="Abandoned science station.",
      structs=[(-70, -30, 100, 70), (60, 20, 80, 90), (-20, 70, 120, 40)],
      crates=[([("electronics", 3), ("circuit_board", 1)], None), ([("rare_science", 1), ("map_fragment", 1)], None),
              ([("tools", 1), ("glass", 2)], None), ([("seeds_bean", 2), ("growing_medium", 1)], None)],
      hazard=("dust_trap", 200, 380, 260)),
 dict(id="ares2", name="Abandoned Outpost Ares-2", kind="outpost", bearing=125, dist=4500, range=1100, ring=230, desc="A full abandoned base. Valuable, hazardous.",
      structs=[(-90, -50, 110, 80), (50, -60, 90, 70), (0, 40, 150, 60), (110, 60, 70, 80), (-110, 70, 60, 60)],
      crates=[([("food_ration", 3), ("water", 2)], None), ([("seeds_potato", 2), ("growing_medium", 2)], None),
              ([("comm_component", 1), ("battery", 1)], None), ([("medical", 1), ("mechanical_parts", 2)], None),
              ([("comm_component", 1), ("battery", 2), ("oxygen_tank", 1)], {"electronic": 1})],
      hazard=("radiation", 70, 600, 380)),
 dict(id="delta", name="Waystation Delta", kind="station", bearing=205, dist=5000, range=1000, ring=150, desc="Remote supply waystation in a cold valley.",
      structs=[(-40, 0, 90, 60), (50, 30, 60, 60)],
      crates=[([("seeds_lettuce", 3), ("seeds_potato", 1)], None), ([("food_ration", 2), ("water", 2)], None),
              ([("growing_medium", 2), ("polymer", 2)], None), ([("battery", 1), ("copper", 1)], None)],
      hazard=("cold", 0, 0, 650)),
 dict(id="relay", name="Mission Relay Station", kind="station", bearing=295, dist=5500, range=1100, ring=170, desc="Old relay tower. Hot rocks all around.",
      structs=[(0, 0, 100, 100), (-100, 50, 70, 60), (100, -40, 70, 60)],
      crates=[([("comm_component", 2), ("copper", 2)], None), ([("circuit_board", 2), ("rare_science", 1)], None), ([("electronics", 2), ("battery", 1)], None)],
      hazard=("radiation", 0, 0, 430)),
]
